//throne8-entry-client/src/config/env.config.ts

// ============================================================
// HELPERS
// ============================================================

function requireEnv(key: string): string {
    const value = process.env[key];
    if (!value || value.trim() === '') {
        // In development, warn but don't crash - env vars load after first request
        if (process.env.NODE_ENV === 'development') {
            console.warn(`⚠️  [CONFIG] Env var not loaded yet at import time: "${key}"`);
            return '';
        }
        throw new Error(
            `\n❌ [CONFIG] Missing required environment variable: "${key}"\n` +
            `   Add it to your .env file and restart the server.\n`
        );
    }
    return value.trim();
}

function optionalEnv(key: string): string {
    return process.env[key]?.trim() ?? "";
}

function numberEnv(key: string, fallback: number): number {
    return Number(process.env[key] || fallback);
}

function booleanEnv(key: string, fallback: boolean): boolean {
    const val = process.env[key];
    if (val === undefined || val === '') return fallback;
    return val === 'true';
}

// ============================================================
// CONFIG
// ============================================================
const _config = {

    // ============================================================
    // 1. CORE API CONFIG
    // ============================================================
    NEXT_PUBLIC_API_BASE_URL: requireEnv('NEXT_PUBLIC_API_BASE_URL'),
    NEXT_PUBLIC_WS_URL: optionalEnv('NEXT_PUBLIC_WS_URL'),
    NEXT_PUBLIC_API_VERSION: optionalEnv('NEXT_PUBLIC_API_VERSION'),
    NEXT_PUBLIC_API_TIMEOUT: numberEnv('NEXT_PUBLIC_API_TIMEOUT', 30000),

    // ============================================================
    // 2. AUTH ENDPOINTS
    // ============================================================
    NEXT_PUBLIC_API_AUTH_ENDPOINT: optionalEnv('NEXT_PUBLIC_API_AUTH_ENDPOINT'),
    NEXT_PUBLIC_REFRESH_TOKEN_ENDPOINT: optionalEnv('NEXT_PUBLIC_REFRESH_TOKEN_ENDPOINT'),
    NEXT_PUBLIC_REGISTER_ENDPOINT: optionalEnv('NEXT_PUBLIC_REGISTER_ENDPOINT'),
    NEXT_PUBLIC_LOGIN_ENDPOINT: optionalEnv('NEXT_PUBLIC_LOGIN_ENDPOINT'),
    NEXT_PUBLIC_PROFILE_ENDPOINT: optionalEnv('NEXT_PUBLIC_PROFILE_ENDPOINT'),
    NEXT_PUBLIC_GET_USER_ENDPOINT: optionalEnv('NEXT_PUBLIC_GET_USER_ENDPOINT'),
    NEXT_PUBLIC_USERS_ENDPOINT: optionalEnv('NEXT_PUBLIC_USERS_ENDPOINT'),
    NEXT_PUBLIC_UPDATE_PROFILE_ENDPOINT: optionalEnv('NEXT_PUBLIC_UPDATE_PROFILE_ENDPOINT'),
    NEXT_PUBLIC_LOGOUT_ENDPOINT: optionalEnv('NEXT_PUBLIC_LOGOUT_ENDPOINT'),


    // ============================================================
    // 3. PROFILE ENDPOINTS
    // ============================================================
    NEXT_PUBLIC_PROFILE_PHOTO_ENDPOINT: optionalEnv('NEXT_PUBLIC_PROFILE_PHOTO_ENDPOINT'),
    NEXT_PUBLIC_COVER_PHOTO_ENDPOINT: optionalEnv('NEXT_PUBLIC_COVER_PHOTO_ENDPOINT'),
    NEXT_PUBLIC_HEADLINE_ENDPOINT: optionalEnv('NEXT_PUBLIC_HEADLINE_ENDPOINT'),
    NEXT_PUBLIC_ABOUT_ENDPOINT: optionalEnv('NEXT_PUBLIC_ABOUT_ENDPOINT'),
    NEXT_PUBLIC_EDUCATION_ENDPOINT: optionalEnv('NEXT_PUBLIC_EDUCATION_ENDPOINT'),
    NEXT_PUBLIC_EXPERIENCE_ENDPOINT: optionalEnv('NEXT_PUBLIC_EXPERIENCE_ENDPOINT'),
    NEXT_PUBLIC_SKILLS_ENDPOINT: optionalEnv('NEXT_PUBLIC_SKILLS_ENDPOINT'),

    // ============================================================
    // 4. ACTIVITY / POSTS ENDPOINTS
    // ============================================================
    NEXT_PUBLIC_ACTIVITY_ENDPOINT: optionalEnv('NEXT_PUBLIC_ACTIVITY_ENDPOINT'),
    NEXT_PUBLIC_FEED_ENDPOINT: optionalEnv('NEXT_PUBLIC_FEED_ENDPOINT'),
    NEXT_PUBLIC_COMMENTS_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMMENTS_ENDPOINT'),

    // ============================================================
    // 5. MENTORSHIP ENDPOINTS
    // ============================================================
    NEXT_PUBLIC_MENTORSHIP_ENDPOINT: optionalEnv('NEXT_PUBLIC_MENTORSHIP_ENDPOINT'),
    NEXT_PUBLIC_MENTOR_CREATE_ENDPOINT: optionalEnv('NEXT_PUBLIC_MENTOR_CREATE_ENDPOINT'),
    NEXT_PUBLIC_MENTOR_BY_ID_ENDPOINT: optionalEnv('NEXT_PUBLIC_MENTOR_BY_ID_ENDPOINT'),
    NEXT_PUBLIC_MENTOR_BY_USER_ENDPOINT: optionalEnv('NEXT_PUBLIC_MENTOR_BY_USER_ENDPOINT'),
    NEXT_PUBLIC_ALL_MENTORS_ENDPOINT: optionalEnv('NEXT_PUBLIC_ALL_MENTORS_ENDPOINT'),

    NEXT_PUBLIC_AVAILABILITY_CREATE_ENDPOINT: optionalEnv('NEXT_PUBLIC_AVAILABILITY_CREATE_ENDPOINT'),
    NEXT_PUBLIC_AVAILABILITY_GET_ALL_DB_ENDPOINT: optionalEnv('NEXT_PUBLIC_AVAILABILITY_GET_ALL_DB_ENDPOINT'),
    NEXT_PUBLIC_AVAILABILITY_BULK_ENDPOINT: optionalEnv('NEXT_PUBLIC_AVAILABILITY_BULK_ENDPOINT'),
    NEXT_PUBLIC_AVAILABILITY_MENTOR_ENDPOINT: optionalEnv('NEXT_PUBLIC_AVAILABILITY_MENTOR_ENDPOINT'),
    NEXT_PUBLIC_AVAILABILITY_UPDATE_ENDPOINT: optionalEnv('NEXT_PUBLIC_AVAILABILITY_UPDATE_ENDPOINT'),
    NEXT_PUBLIC_AVAILABILITY_DELETE_ENDPOINT: optionalEnv('NEXT_PUBLIC_AVAILABILITY_DELETE_ENDPOINT'),
    NEXT_PUBLIC_AVAILABILITY_STATS_ENDPOINT: optionalEnv('NEXT_PUBLIC_AVAILABILITY_STATS_ENDPOINT'),

    NEXT_PUBLIC_SESSIONS_ENDPOINT: optionalEnv('NEXT_PUBLIC_SESSIONS_ENDPOINT'),
    NEXT_PUBLIC_SESSIONS_CREATE_ENDPOINT: optionalEnv('NEXT_PUBLIC_SESSIONS_CREATE_ENDPOINT'),
    NEXT_PUBLIC_SESSIONS_GET_ALL_ENDPOINT: optionalEnv('NEXT_PUBLIC_SESSIONS_GET_ALL_ENDPOINT'),
    NEXT_PUBLIC_SESSIONS_GET_ALL_DB_ENDPOINT: optionalEnv('NEXT_PUBLIC_SESSIONS_GET_ALL_DB_ENDPOINT'),
    NEXT_PUBLIC_SESSIONS_MENTOR_ENDPOINT: optionalEnv('NEXT_PUBLIC_SESSIONS_MENTOR_ENDPOINT'),
    NEXT_PUBLIC_SESSIONS_BOOK_ENDPOINT: optionalEnv('NEXT_PUBLIC_SESSIONS_BOOK_ENDPOINT'),

    // ============================================================
    // 6. NOTIFICATIONS ENDPOINT
    // ============================================================
    NEXT_PUBLIC_NOTIFICATIONS_ENDPOINT: optionalEnv('NEXT_PUBLIC_NOTIFICATIONS_ENDPOINT'),
    NEXT_PUBLIC_NOTIFICATIONS_ALL_MARKED_READ_ENDPOINT: optionalEnv('NEXT_PUBLIC_NOTIFICATIONS_ALL_MARKED_READ_ENDPOINT'),

    // ==============================================================
    // 7. STUDY GROUP ENDPOINTS
    // ==============================================================
    NEXT_PUBLIC_STUDY_GROUPS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUPS_ENDPOINT'),
    NEXT_PUBLIC_MY_STUDY_GROUPS_ENDPOINT: optionalEnv('NEXT_PUBLIC_MY_STUDY_GROUPS_ENDPOINT'),
    NEXT_PUBLIC_CREATE_STUDY_GROUP_ENDPOINT: optionalEnv('NEXT_PUBLIC_CREATE_STUDY_GROUP_ENDPOINT'),
    NEXT_PUBLIC_TOP_RANKED_STUDY_GROUPS_ENDPOINT: optionalEnv('NEXT_PUBLIC_TOP_RANKED_STUDY_GROUPS_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_MEMBER_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_MEMBER_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_SEARCH_GROUPS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_SEARCH_GROUPS_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_SEARCH_POPULAR_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_SEARCH_POPULAR_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_SEARCH_TRENDING_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_SEARCH_TRENDING_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_SEARCH_RECOMMENDED_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_SEARCH_RECOMMENDED_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_SEARCH_CATEGORY_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_SEARCH_CATEGORY_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_SEARCH_AVAILABLE_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_SEARCH_AVAILABLE_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_JOIN_REQUEST_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_JOIN_REQUEST_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_MESSAGES_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_MESSAGES_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_FILES_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_FILES_ENDPOINT'),

    NEXT_PUBLIC_STUDY_GROUP_SEARCH_TAGS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_SEARCH_TAGS_ENDPOINT'),

    NEXT_PUBLIC_STUDY_GROUP_TIMER_START_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_TIMER_START_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_TIMER_PAUSE_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_TIMER_PAUSE_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_TIMER_RESUME_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_TIMER_RESUME_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_TIMER_STOP_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_TIMER_STOP_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_TIMER_CANCEL_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_TIMER_CANCEL_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_TIMER_ACTIVE_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_TIMER_ACTIVE_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_TIMER_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_TIMER_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_TIMER_TODAY_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_TIMER_TODAY_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_TIMER_STATS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_TIMER_STATS_ENDPOINT'),


    NEXT_PUBLIC_STUDY_GROUP_GOALS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_GOALS_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_GOAL_COMPLETE_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_GOAL_COMPLETE_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_GOAL_INCOMPLETE_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_GOAL_INCOMPLETE_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_GOALS_ACTIVE_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_GOALS_ACTIVE_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_GOALS_STATS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_GOALS_STATS_ENDPOINT'),

    NEXT_PUBLIC_STUDY_GROUP_DASHBOARD_USER_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_DASHBOARD_USER_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_DASHBOARD_GROUP_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_DASHBOARD_GROUP_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_PERFORMANCE_ANALYTICS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_PERFORMANCE_ANALYTICS_ENDPOINT'),

    NEXT_PUBLIC_STUDY_GROUP_TASKS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_TASKS_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_TASK_COMPLETE_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_TASK_COMPLETE_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_TASK_INCOMPLETE_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_TASK_INCOMPLETE_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_TASKS_STATS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_TASKS_STATS_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_TASKS_UPCOMING_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_TASKS_UPCOMING_ENDPOINT'),

    NEXT_PUBLIC_STUDY_GROUP_DASHBOARD_STATISTICS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_DASHBOARD_STATISTICS_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_DASHBOARD_ANALYTICS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_DASHBOARD_ANALYTICS_ENDPOINT'),

    NEXT_PUBLIC_STUDY_GROUP_TASKS_OVERDUE_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_TASKS_OVERDUE_ENDPOINT'),

    NEXT_PUBLIC_STUDY_GROUP_JOIN_REQUESTS_MY_REQUESTS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_JOIN_REQUESTS_MY_REQUESTS_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_JOIN_REQUESTS_GROUP_REQUESTS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_JOIN_REQUESTS_GROUP_REQUESTS_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_JOIN_REQUESTS_RESPOND_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_JOIN_REQUESTS_RESPOND_ENDPOINT'),

    NEXT_PUBLIC_STUDY_GROUP_CHAT_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_CHAT_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_CHAT_MESSAGE_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_CHAT_MESSAGE_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_FILES_UPLOAD_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_FILES_UPLOAD_ENDPOINT'),

    NEXT_PUBLIC_STUDY_GROUP_DOUBTS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_DOUBTS_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_DOUBTS_ANSWER_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_DOUBTS_ANSWER_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_DOUBTS_SEARCH_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_DOUBTS_SEARCH_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_DOUBTS_USER_MY_DOUBTS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_DOUBTS_USER_MY_DOUBTS_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_DOUBTS_CATEGORY_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_DOUBTS_CATEGORY_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_DOUBTS_USER_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_DOUBTS_USER_ENDPOINT'),

    NEXT_PUBLIC_STUDY_GROUP_LIVE_ROOMS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_LIVE_ROOMS_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_LIVE_ROOMS_GROUP_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_LIVE_ROOMS_GROUP_ENDPOINT'),

    NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_CHECK_IN_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_CHECK_IN_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_AUTO_MARK_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_AUTO_MARK_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_GROUP_STATS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_GROUP_STATS_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_USER_STATS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_USER_STATS_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_STATUS_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_STATUS_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_PERCENTAGE_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_PERCENTAGE_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_HISTORY_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_HISTORY_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_CALENDAR_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_CALENDAR_ENDPOINT'),

    NEXT_PUBLIC_STUDY_GROUP_SHARE_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_SHARE_ENDPOINT'),
    NEXT_PUBLIC_STUDY_GROUP_SHARE_VALIDATE_ENDPOINT: optionalEnv('NEXT_PUBLIC_STUDY_GROUP_SHARE_VALIDATE_ENDPOINT'),


    //=================================================================
    // 8. COMPANY ENDPOINTS
    //=================================================================
    NEXT_PUBLIC_COMPANY_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_CREATE_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_CREATE_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_BY_ID_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_BY_ID_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_UPDATE_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_UPDATE_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_DELETE_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_DELETE_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_GET_ALL_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_GET_ALL_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_COMPANIES_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_COMPANIES_ENDPOINT'),

    NEXT_PUBLIC_COMPANY_ANALYTICS_DASHBOARD_V2_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_ANALYTICS_DASHBOARD_V2_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_ANALYTICS_COMPANY_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_ANALYTICS_COMPANY_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_ANALYTICS_TOP_POSTS_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_ANALYTICS_TOP_POSTS_ENDPOINT'),

    NEXT_PUBLIC_COMPANY_EMPLOYEES_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_EMPLOYEES_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_EVENTS_CREATE_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_EVENTS_CREATE_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_EVENTS_GET_ALL_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_EVENTS_GET_ALL_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_ANALYTICS_TRACK_USER_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_ANALYTICS_TRACK_USER_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_EMPLOYEE_GET_BY_ID_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_EMPLOYEE_GET_BY_ID_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_EMPLOYEES_COMPANIES_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_EMPLOYEES_COMPANIES_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_EMPLOYEE_ADVOCACY_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_EMPLOYEE_ADVOCACY_ENDPOINT'),

    NEXT_PUBLIC_COMPANY_POSTS_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_POSTS_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_POSTS_CREATE_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_POSTS_CREATE_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_POSTS_COMPANY_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_POSTS_COMPANY_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_POSTS_DELETE_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_POSTS_DELETE_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_POSTS_LIKE_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_POSTS_LIKE_ENDPOINT'),
    NEXT_PUBLIC_COMPANY_POSTS_UNLIKE_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_POSTS_UNLIKE_ENDPOINT'),

    NEXT_PUBLIC_COMPANY_CONNECTIONS_FOLLOW_ENDPOINT: optionalEnv('NEXT_PUBLIC_COMPANY_CONNECTIONS_FOLLOW_ENDPOINT'),

    // ============================================================
    // 9 . CONNECTIONS ENDPOINTS
    // ============================================================

    NEXT_PUBLIC_CONNECTIONS_REQUESTS_ENDPOINT: optionalEnv('NEXT_PUBLIC_CONNECTIONS_REQUESTS_ENDPOINT'),
    NEXT_PUBLIC_FOLLOW_ENDPOINT: optionalEnv('NEXT_PUBLIC_FOLLOW_ENDPOINT'),
    NEXT_PUBLIC_CONNECTIONS_REQUESTS_USER_ENDPOINT: optionalEnv('NEXT_PUBLIC_CONNECTIONS_REQUESTS_USER_ENDPOINT'),
    NEXT_PUBLIC_CONNECTIONS_CONNECTION_USER_ENDPOINT: optionalEnv('NEXT_PUBLIC_CONNECTIONS_CONNECTION_USER_ENDPOINT'),
    NEXT_PUBLIC_CONNECTIONS_USER_ENDPOINT: optionalEnv('NEXT_PUBLIC_CONNECTIONS_USER_ENDPOINT'),




       ///////////////////////// changed 
    NEXT_PUBLIC_FOLLOW_COUNTS_ENDPOINT: optionalEnv('NEXT_PUBLIC_FOLLOW_COUNTS_ENDPOINT'),
    // ============================================================
    // 10. MESSAGES ENDPOINTS
    // ============================================================

    NEXT_PUBLIC_MESSAGES_CONVERSATIONS_ENDPONT: optionalEnv('NEXT_PUBLIC_MESSAGES_CONVERSATIONS_ENDPONT'),
    NEXT_PUBLIC_MESSAGES_DIRECT_ENDPOINT: optionalEnv('NEXT_PUBLIC_MESSAGES_DIRECT_ENDPOINT'),
    NEXT_PUBLIC_MESSAGES_MESSAGES_ENDPOINT: optionalEnv('NEXT_PUBLIC_MESSAGES_MESSAGES_ENDPOINT'),
    NEXT_PUBLIC_MESSAGES_REACT_ENDPOINT: optionalEnv('NEXT_PUBLIC_MESSAGES_REACT_ENDPOINT'),
    NEXT_PUBLIC_MESSAGES_CONVERSATIONS_ENDPOINT: optionalEnv('NEXT_PUBLIC_MESSAGES_CONVERSATIONS_ENDPOINT'),

    // ============================================================
    // 11. VERIFY ENDPOINTS
    // ============================================================

    NEXT_PUBLIC_VERIFY_EMAIL_SEND_OTP_ENDPOINT: optionalEnv('NEXT_PUBLIC_VERIFY_EMAIL_SEND_OTP_ENDPOINT'),
    NEXT_PUBLIC_VERIFY_EMAIL_VERIFY_OTP_ENDPOINT: optionalEnv('NEXT_PUBLIC_VERIFY_EMAIL_VERIFY_OTP_ENDPOINT'),
    NEXT_PUBLIC_VERIFY_EMAIL_RESEND_OTP_ENDPOINT: optionalEnv('NEXT_PUBLIC_VERIFY_EMAIL_RESEND_OTP_ENDPOINT'),
    NEXT_PUBLIC_VERIFY_EMAIL_STATUS_CHECK_ENDPOINT: optionalEnv('NEXT_PUBLIC_VERIFY_EMAIL_STATUS_CHECK_ENDPOINT'),

    NEXT_PUBLIC_VERIFY_PHONE_SEND_OTP_ENDPOINT: optionalEnv('NEXT_PUBLIC_VERIFY_PHONE_SEND_OTP_ENDPOINT'),
    NEXT_PUBLIC_VERIFY_PHONE_VERIFY_OTP_ENDPOINT: optionalEnv('NEXT_PUBLIC_VERIFY_PHONE_VERIFY_OTP_ENDPOINT'),
    NEXT_PUBLIC_VERIFY_PHONE_RESEND_OTP_ENDPOINT: optionalEnv('NEXT_PUBLIC_VERIFY_PHONE_RESEND_OTP_ENDPOINT'),
    NEXT_PUBLIC_VERIFY_PHONE_STATUS_CHECK_ENDPOINT: optionalEnv('NEXT_PUBLIC_VERIFY_PHONE_STATUS_CHECK_ENDPOINT'),

    NEXT_PUBLIC_VERIFY_IDENTITY_AADHAAR_SEND_OTP_ENDPOINT: optionalEnv('NEXT_PUBLIC_VERIFY_IDENTITY_AADHAAR_SEND_OTP_ENDPOINT'),
    NEXT_PUBLIC_VERIFY_IDENTITY_AADHAAR_VERIFY_OTP_ENDPOINT: optionalEnv('NEXT_PUBLIC_VERIFY_IDENTITY_AADHAAR_VERIFY_OTP_ENDPOINT'),
    NEXT_PUBLIC_VERIFY_IDENTITY_AADHAAR_RESEND_OTP_ENDPOINT: optionalEnv('NEXT_PUBLIC_VERIFY_IDENTITY_AADHAAR_RESEND_OTP_ENDPOINT'),
    NEXT_PUBLIC_VERIFY_IDENTITY_AADHAAR_STATUS_CHECK_ENDPOINT: optionalEnv('NEXT_PUBLIC_VERIFY_IDENTITY_AADHAAR_STATUS_CHECK_ENDPOINT'),

    NEXT_PUBLIC_VERIFY_EMAIL_COMPANY_EMAIL_SEND_OTP_ENDPOINT: optionalEnv('NEXT_PUBLIC_VERIFY_EMAIL_COMPANY_EMAIL_SEND_OTP_ENDPOINT'),
    NEXT_PUBLIC_VERIFY_EMAIL_COMPANY_EMAIL_VERIFY_OTP_ENDPOINT: optionalEnv('NEXT_PUBLIC_VERIFY_EMAIL_COMPANY_EMAIL_VERIFY_OTP_ENDPOINT'),
    NEXT_PUBLIC_VERIFY_EMAIL_COMPANY_EMAIL_RESEND_OTP_ENDPOINT: optionalEnv('NEXT_PUBLIC_VERIFY_EMAIL_COMPANY_EMAIL_RESEND_OTP_ENDPOINT'),
    NEXT_PUBLIC_VERIFY_EMAIL_COMPANY_EMAIL_STATUS_CHECK_ENDPOINT: optionalEnv('NEXT_PUBLIC_VERIFY_EMAIL_COMPANY_EMAIL_STATUS_CHECK_ENDPOINT'),






    // ============================================================
    // 7. CLOUDINARY
    // ============================================================
    NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: requireEnv('NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME'),
    NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET: requireEnv('NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET'),
    NEXT_PUBLIC_CLOUDINARY_BASE_URL: optionalEnv('NEXT_PUBLIC_CLOUDINARY_BASE_URL'),

    // ============================================================
    // 8. APP CONFIG
    // ============================================================
    NEXT_PUBLIC_APP_URL: requireEnv('NEXT_PUBLIC_APP_URL'),
    NEXT_PUBLIC_APP_NAME: requireEnv('NEXT_PUBLIC_APP_NAME'),
    NEXT_PUBLIC_APP_ENV: requireEnv('NEXT_PUBLIC_APP_ENV'),

    // ============================================================
    // 9. FILE UPLOAD LIMITS
    // ============================================================
    NEXT_PUBLIC_MAX_PHOTO_SIZE: numberEnv('NEXT_PUBLIC_MAX_PHOTO_SIZE', 5242880),
    NEXT_PUBLIC_MAX_COVER_SIZE: numberEnv('NEXT_PUBLIC_MAX_COVER_SIZE', 8388608),
    NEXT_PUBLIC_MAX_VIDEO_SIZE: numberEnv('NEXT_PUBLIC_MAX_VIDEO_SIZE', 52428800),
    NEXT_PUBLIC_ALLOWED_IMAGE_TYPES: optionalEnv('NEXT_PUBLIC_ALLOWED_IMAGE_TYPES'),

    // ============================================================
    // 10. PAGINATION DEFAULTS
    // ============================================================
    NEXT_PUBLIC_DEFAULT_PAGE_SIZE: numberEnv('NEXT_PUBLIC_DEFAULT_PAGE_SIZE', 20),
    NEXT_PUBLIC_MAX_PAGE_SIZE: numberEnv('NEXT_PUBLIC_MAX_PAGE_SIZE', 50),

    // ============================================================
    // 11. FEATURE FLAGS
    // ============================================================
    NEXT_PUBLIC_ENABLE_MASTERCLASSES: booleanEnv('NEXT_PUBLIC_ENABLE_MASTERCLASSES', true),
    NEXT_PUBLIC_ENABLE_COMPARE: booleanEnv('NEXT_PUBLIC_ENABLE_COMPARE', true),
    NEXT_PUBLIC_ENABLE_FIND_MENTOR: booleanEnv('NEXT_PUBLIC_ENABLE_FIND_MENTOR', true),
    NEXT_PUBLIC_ENABLE_NOTIFICATIONS: booleanEnv('NEXT_PUBLIC_ENABLE_NOTIFICATIONS', true),

    // ============================================================
    // 12. ANALYTICS
    // ============================================================
    NEXT_PUBLIC_GA_MEASUREMENT_ID: optionalEnv('NEXT_PUBLIC_GA_MEASUREMENT_ID'),
    NEXT_PUBLIC_POSTHOG_KEY: optionalEnv('NEXT_PUBLIC_POSTHOG_KEY'),
    NEXT_PUBLIC_POSTHOG_HOST: optionalEnv('NEXT_PUBLIC_POSTHOG_HOST'),

    // ============================================================
    // 13. PAYMENTS
    // ============================================================
    NEXT_PUBLIC_RAZORPAY_KEY_ID: optionalEnv('NEXT_PUBLIC_RAZORPAY_KEY_ID'),
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: optionalEnv('NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY'),

    // ============================================================
    // 14. OAUTH CLIENT IDs
    // ============================================================
    NEXT_PUBLIC_GOOGLE_CLIENT_ID: optionalEnv('NEXT_PUBLIC_GOOGLE_CLIENT_ID'),
    NEXT_PUBLIC_LINKEDIN_CLIENT_ID: optionalEnv('NEXT_PUBLIC_LINKEDIN_CLIENT_ID'),


} as const;

const config = Object.freeze(_config);

export default config;

