import { Job } from '@/features/jobs/types/jobs'

export const CATEGORIES = ['Marketing', 'Web Development', 'Sales', 'HR']

export const MOCK_JOBS: Job[] = [
  {
    id: '1', title: 'Senior Product Designer', company: 'Throne8', companyLogo: 'T8',
    location: 'San Francisco, CA', salary: { min: 130000, max: 180000, currency: 'USD' },
    type: 'full-time', experience: 'senior', workMode: 'hybrid',
    tags: ['Figma', 'Design Systems', 'User Research', 'Prototyping'],
    description: "We're building the future of digital commerce and need a visionary designer to lead our product experience. You'll shape interfaces used by millions.",
    responsibilities: ['Lead end-to-end design for core product features', 'Build and maintain our design system', 'Collaborate with engineers and PMs', 'Conduct user research', 'Mentor junior designers'],
    requirements: ['5+ years product design experience', 'Expert-level Figma', 'Strong portfolio', 'Design systems at scale'],
    benefits: ['Equity package', 'Remote flexibility', '$5k equipment budget', 'Health & dental', 'Unlimited PTO'],
    postedAt: '2025-03-01', deadline: '2025-04-15', applicants: 142, featured: true, category: 'Design',
  },
  {
    id: '2', title: 'Staff Software Engineer', company: 'Nexus Labs', companyLogo: 'NL',
    location: 'New York, NY', salary: { min: 200000, max: 280000, currency: 'USD' },
    type: 'full-time', experience: 'lead', workMode: 'remote',
    tags: ['TypeScript', 'React', 'Node.js', 'AWS', 'GraphQL'],
    description: 'Join our elite engineering team building distributed systems that process billions of events daily.',
    responsibilities: ['Architect scalable backend services', 'Drive technical roadmap', 'Lead cross-functional initiatives', 'Mentor engineers'],
    requirements: ['8+ years software engineering', 'Distributed systems expertise', 'Strong TypeScript/React', 'Technical leadership'],
    benefits: ['Top-tier equity', 'Full remote', '$10k learning budget', 'Comprehensive health', '401k matching'],
    postedAt: '2025-03-03', deadline: '2025-04-20', applicants: 89, featured: true, category: 'Engineering',
  },
  {
    id: '3', title: 'Growth Marketing Lead', company: 'Orbit', companyLogo: 'OR',
    location: 'Austin, TX', salary: { min: 95000, max: 135000, currency: 'USD' },
    type: 'full-time', experience: 'mid', workMode: 'hybrid',
    tags: ['SEO', 'Paid Ads', 'Analytics', 'A/B Testing', 'Email'],
    description: "Scale Orbit's user acquisition engine from 100k to 1M users. Own the full funnel, run experiments relentlessly.",
    responsibilities: ['Own user acquisition across all channels', 'Run growth experiments', 'Build performance dashboards', 'Manage $2M+ budget'],
    requirements: ['4+ years growth marketing', 'Proven scaling track record', 'Strong SQL skills', 'Ad platform experience'],
    benefits: ['Performance bonuses', 'Flexible PTO', 'Remote Fridays', 'Health benefits', 'Team retreats'],
    postedAt: '2025-03-04', deadline: '2025-04-10', applicants: 203, featured: false, category: 'Marketing',
  },
  {
    id: '4', title: 'AI/ML Research Engineer', company: 'Deepmind Co', companyLogo: 'DC',
    location: 'Seattle, WA', salary: { min: 180000, max: 260000, currency: 'USD' },
    type: 'full-time', experience: 'senior', workMode: 'onsite',
    tags: ['Python', 'PyTorch', 'LLMs', 'MLOps', 'CUDA'],
    description: "Push the boundaries of AI. Work on frontier models, novel architectures, and deploy cutting-edge systems.",
    responsibilities: ['Research novel ML architectures', 'Scale training pipelines', 'Publish research', 'Collaborate on AI features'],
    requirements: ['PhD or equivalent in ML/CS', 'Deep PyTorch expertise', 'Published research preferred', 'Distributed training experience'],
    benefits: ['Research budget', 'Conference attendance', 'Top-tier equity', 'Onsite meals', 'Gym stipend'],
    postedAt: '2025-02-28', deadline: '2025-04-30', applicants: 67, featured: true, category: 'Engineering',
  },
  {
    id: '5', title: 'Head of Product', company: 'Forma', companyLogo: 'FM',
    location: 'Los Angeles, CA', salary: { min: 175000, max: 230000, currency: 'USD' },
    type: 'full-time', experience: 'executive', workMode: 'hybrid',
    tags: ['Product Strategy', 'Roadmapping', 'OKRs', 'Agile', 'B2B SaaS'],
    description: "Define the product vision for Forma's B2B SaaS platform. Lead a team of 12 PMs.",
    responsibilities: ['Own product vision and roadmap', 'Lead 12 product managers', 'Work with engineering on strategy', 'Present to board'],
    requirements: ['10+ years product management', 'Experience leading PM teams', 'Deep B2B SaaS expertise', '0-to-1 track record'],
    benefits: ['Executive equity', 'Board exposure', 'Relocation assistance', 'Premium health', 'Company car'],
    postedAt: '2025-03-05', deadline: '2025-05-01', applicants: 44, featured: false, category: 'Product',
  },
  {
    id: '6', title: 'Frontend Engineer', company: 'Pulse', companyLogo: 'PL',
    location: 'Remote', salary: { min: 110000, max: 155000, currency: 'USD' },
    type: 'full-time', experience: 'mid', workMode: 'remote',
    tags: ['React', 'Next.js', 'TypeScript', 'Tailwind', 'WebGL'],
    description: "Build beautiful, performant interfaces for Pulse's real-time analytics platform.",
    responsibilities: ['Build React component library', 'Implement data visualizations', 'Optimize Core Web Vitals', 'Collaborate with designers'],
    requirements: ['4+ years React experience', 'Expert TypeScript', 'Data visualization experience', 'Strong design sense'],
    benefits: ['Full remote', 'Home office stipend', 'Open source time', 'Health benefits', 'Flexible hours'],
    postedAt: '2025-03-06', deadline: '2025-04-25', applicants: 178, featured: false, category: 'Engineering',
  },
  {
    id: '7', title: 'Brand Designer', company: 'Luxe Commerce', companyLogo: 'LC',
    location: 'Miami, FL', salary: { min: 75000, max: 110000, currency: 'USD' },
    type: 'full-time', experience: 'mid', workMode: 'onsite',
    tags: ['Brand Identity', 'Motion Design', 'After Effects', 'Illustration'],
    description: 'Define the visual identity for one of the fastest-growing luxury e-commerce brands.',
    responsibilities: ['Own brand identity', 'Create multi-channel campaigns', 'Develop motion graphics', 'Work with external agencies'],
    requirements: ['3+ years brand design', 'Strong motion design', 'Luxury brand experience preferred', 'Excellent portfolio'],
    benefits: ['Employee discounts', 'Creative budget', 'Health benefits', 'Miami office perks', 'Team events'],
    postedAt: '2025-03-02', deadline: '2025-04-12', applicants: 312, featured: false, category: 'Design',
  },
  {
    id: '8', title: 'DevOps / Platform Engineer', company: 'Strata', companyLogo: 'ST',
    location: 'Chicago, IL', salary: { min: 130000, max: 170000, currency: 'USD' },
    type: 'full-time', experience: 'senior', workMode: 'hybrid',
    tags: ['Kubernetes', 'Terraform', 'AWS', 'CI/CD', 'Go'],
    description: "Build and scale the infrastructure backbone powering Strata's financial data platform.",
    responsibilities: ['Design Kubernetes infrastructure', 'Build CI/CD pipelines', 'Implement security systems', 'On-call rotation'],
    requirements: ['6+ years DevOps/SRE', 'Deep Kubernetes expertise', 'Strong Terraform skills', 'Financial services a plus'],
    benefits: ['On-call pay', 'Certification budget', 'Health benefits', 'Hybrid schedule', 'Strong 401k'],
    postedAt: '2025-03-01', deadline: '2025-04-20', applicants: 56, featured: false, category: 'Engineering',
  },
]